<?php

$data = [
	[
    'author' => 'Jillian',
    'story-number' => 1,
    'location' => 'Lunan Bay Farm - Angus',
    'text' => 'The current coronavirus pandemic has hugely impacted our business. Most of our asparagus had been presold to restaurants so we had to pivot to new markets. Luckily the response from small independent retailers has been amazing! We hope that these new routes will remain an outlet once the restaurants reopen. It’s not yet clear what the financial impact on our bottom line will be as we are just going into the season now but we are upbeat. Later in the year when our goat meat season starts, we may face a similar issue but we have already had a number of inquiries so we are hopeful that it restaurants have not reopened we can find new local markets.',
    'title' => 'We are upbeat',
    'source' => 'Covid Chronicle',
    'storyDate' => '15.5.20',
    'storyDateFormatted' => '2020-05-15',
    'categories' => 'Supply chains, Local economy',
    'imported' => 1,
  ],
	[
    'author' => 'Daya',
    'story-number' => 2,
    'location' => 'Edinburgh',
    'text' => 'My experience of C19 lockdown confirms the argument in favour of small local shops and how they reacted much better than supermarkets. Being independent / community-run, they have demonstrated greater flexibility as they were able to respond much faster to the changes and their community’s needs. I was super impressed with the Penicuik Storehouse, how fast they organised and coordinated the collections and deliveries around town. While people were saying they could not get any slots for the ‘big four’, the Storehouse staff & volunteers were working hard in the shop, stocking up, packing, and out delivering groceries every day. They also had a table outside with a plastic screen (at least 2 weeks before supermarkets even started using them!), enabling people to collect orders or make a purchase without having to enter the small shop. The supermarkets were slow to react; first running out of food then overstocking and wasting, also waiting for weeks to receive orders from some distant head office and then take time to implement across the numerous branches, with staff confused, abused and overworked, often on short-term, low paid contracts. This is something we need to remember and demand change to the food system for the future.',
    'title' => 'Slow to react',
    'source' => 'Covid Chronicle',
    'storyDate' => '15.5.20',
    'storyDateFormatted' => '2020-05-15',
    'categories' => 'Food insecurity, Supply chains',
    'imported' => 1,
  ],
	[
    'author' => 'Niamh',
    'story-number' => 3,
    'location' => 'West Lothian',
    'text' => 'As the country went into lockdown, my family and I had to adjust the way we shop. Before COVID-19, it was so convenient to pop to shops whenever we needed ingredients for dinner. However with a little bit of forward planning, we have went from making daily visits to the supermarkets pre-lockdown, to just one visit to the supermarket per week during lockdown. My mum is a NHS key worker, so we want to completely minimise our exposure to large gatherings of people and risk of infection. As a family it has made us conscious not only of what ingredients go into our meals and how we can use these efficiently throughout the week, the COVID lockdown has made us aware of our carbon footprint through the countless car journeys we would make to get food on the table. Before, daily car trips to get a basket of items – we were clocking up fuel consumption and so, emissions. Making this change to our daily/weekly life during COVID has been eye-opening that our previous habits were unsustainable – I don’t think we will go back to the way it was before.',
    'title' => 'Previous habits were unsustainable',
    'source' => 'Covid Chronicle',
    'storyDate' => '29.5.20',
    'storyDateFormatted' => '2020-05-29',
    'categories' => 'Physical health, Environmental concerns',
    'imported' => 1,
  ],
	[
    'author' => 'Fiona',
    'story-number' => 4,
    'location' => 'West Lothian',
    'text' => 'My family have always loved home-baking, it is a great way to bring families together, it has always been this way. During lockdown there has been notable shortages of certain ingredients at the supermarkets, forcing us to get creative with what we make. Particularly, we have struggled to get yeast and bread flour. Our neighbour had created a sourdough starter and gave us a jar, it has been a great addition to our kitchen. I love the idea that we will always have a readily available source from which to make bread. The sourdough starter has really expanded our horizons in home-baking, showing us, you can make just about anything that we would previously have bought the mass-produced version from the supermarket. We have made delicious fresh bread, bagels, cinnamon rolls and fruitcake. Knowing that our food has been made with humble hands in our own kitchen is so comforting during these uncertain times.',
    'title' => 'Comforting during these uncertain times',
    'source' => 'Covid Chronicle',
    'storyDate' => '1.6.20',
    'storyDateFormatted' => '2020-06-01',
    'categories' => 'Community sharing, Cooking',
    'imported' => '',
  ],
	[
    'author' => 'Morgan',
    'story-number' => 5,
    'location' => 'Falkirk',
    'text' => 'I have been a vegetarian for almost 20 years mainly for welfare issues but also because I do not like the thought of my food being pumped with chemicals. Due to the coronavirus outbreak, I have noticed more people are buying fruit and veg locally, myself included. I want to keep local businesses alive. I also feel that my local farm shops have better quality fruit and veg compared to supermarkets, and they are more sustainably packaged too (often coming \'naked\' or in a paper bag which I am fine with). It is more expensive but I dont mind paying extra to help local businesses, and if I am getting quality and, in my opinion, healthier products.',
    'title' => 'Keep local businesses alive',
    'source' => 'Covid Chronicle',
    'storyDate' => '4.6.20',
    'storyDateFormatted' => '2020-06-04',
    'categories' => 'Local economy, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Elaine',
    'story-number' => 6,
    'location' => 'Perth',
    'text' => 'I have been pleasantly surprised that on the whole the food system has worked well. I was scared when folks started panic buying but resisted it and thankfully things settled. Flour and yeast are like gold dust but generally I\'ve been able to get everything else. I\'ve bought mainly from the village shop and local farm shops, only using supermarkets 3 times in 8 weeks. Usually I mainly use supermarket. I have been inspired to plant tatties, onions, parsnips, 2 apple trees, 2 blueberry bushes, raspberries, strawberries and rhubarb this year.',
    'title' => 'I have been inspired',
    'source' => 'Covid Chronicle',
    'storyDate' => '4.6.20',
    'storyDateFormatted' => '2020-06-04',
    'categories' => 'Food insecurity, Supply chains, Cooking',
    'imported' => '',
  ],
	[
    'author' => 'Judy',
    'story-number' => 7,
    'location' => 'Glasgow',
    'text' => 'Allotments really helped those of us fortunate enough to have one, cope with the crisis. However the other day a father outside the site said to me, ‘My family and I would love to help you, we are willing to dig or do anything’. I asked if he had his name down for a plot but he replied ‘No, there is no point, I want it for my sons now so they can experience how things grow but there is a 10 year waiting list. The people over there have gardens but we live in these flats without anything. It is so difficult at the moment’ . I felt sad. I wittered on about stalled spaces, community gardens and the legislation in the Community Empowerment (Scotland) Act 2015 that local authorities have a duty to provide allotments. I knew that was no real help to him. He wants a patch of ground of his own - now. He wants a place where his children can nurture plants and flowers and be nurtured by them. This is why I campaign for more Allotments - People’s Gardens available for everyone. The experience this year has confirmed more than ever that we need them if we are to survive.',
    'title' => 'Allotments really helped',
    'source' => 'Covid Chronicle',
    'storyDate' => '4.6.20',
    'storyDateFormatted' => '2020-06-04',
    'categories' => 'Community sharing, Food insecurity, Seasonal growing, Mental health, Green space',
    'imported' => '',
  ],
	[
    'author' => 'Azharah',
    'story-number' => 8,
    'location' => 'St Andrews',
    'text' => 'Covid time with mum age 89. Tubs of flowers planted for visitors in empty streets, see their beauty at every stage  on our slow walks . Polite communications, smiles good mornings as never before in St. Andrews, fresh fresh divinely fresh air and wild bird song. Nowhere for a coffee. Tractors barrelling through North street, why they are going so fast? Emotional? Mum fainted out on a walk with me. Scary. Social distancing evaporates as passers by help. Angels in the shape of ambulance men share their calm wisdom. Human beings are amazing. How fragile life is sometimes, slowing down to make bridges and acting quickly to save things.',
    'title' => 'Human beings are amazing',
    'source' => 'Covid Chronicle',
    'storyDate' => '30.5.20',
    'storyDateFormatted' => '2020-05-30',
    'categories' => 'Community sharing, Isolation, Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Niamh',
    'story-number' => 9,
    'location' => 'West Lothian',
    'text' => 'I live in West Lothian, where the main source of food comes from major supermarket chains. There is very few shops selling locally sourced food. During lockdown, my neighbour created a Garden Co-op. We live in a small rural community, the Co-op has enabled my neighbours and I to share crops from our gardens in a socially distant way. The Garden Co-op has been really popular: it has given households, who do not have vegetable patches in their garden, the opportunity to grow their own vegetables. In the Co-op my neighbours and I have shared crops of Brussel sprouts, tomatoes, lettuce, and more. The Co-op has created a sense of community during these difficult times, it has engaged families to grow their own food thus positive attitude changes towards how we source food. My hope is that the Garden Co-op will continue long after lockdown and continue to promote a sense of community and nutritional food.',
    'title' => 'Engaged families to grow',
    'source' => 'Covid Chronicle',
    'storyDate' => '7.6.20',
    'storyDateFormatted' => '2020-06-07',
    'categories' => 'Community sharing, Food insecurity, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Tracy',
    'story-number' => 10,
    'location' => 'Edinburgh',
    'text' => 'I feel very lucky that I have been spending so much time at my allotment over the Covid-19 Lockdown period. Lucky is not really the word, as it took over 6 years of waiting for an allotment, and a lot of hard work tending it, to be able to harvest lovely fresh food. You have to WANT to grow your own food. Some people sadly have no idea how rewarding it is. I grow my own as I prefer home-grown food without air miles, pesticides and chemicals. You can also enjoy super fresh salads! We love having a BBQ at the plot, and cooking freshly picked vegetables... I cook from scratch a lot and shop for ingredients like some ladies shop for clothes. With Brexit looming, increasingly my allotment has also signified food security. We shop locally and support small Leith businesses, but what Covid-19 has taught me is that growing your own food as is good for your mental health as it is for your physical health. It is a connection to this earth. Scotland needs more allotments and more gardening education, we have the space and we should lead by example in the UK.',
    'title' => 'A connection to this earth',
    'source' => 'Covid Chronicle',
    'storyDate' => '15.6.20',
    'storyDateFormatted' => '2020-06-15',
    'categories' => 'Food insecurity, Cooking, Local economy, Seasonal growing, Inequality, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Anonymous',
    'story-number' => 11,
    'location' => 'Glasgow',
    'text' => 'I was so grateful for fresh fruit and some food each week from Blackhill’s growing group. I was having panic attacks at the thought of having to go to the shops. I don’t have good patience for queues at the best of times so having to stand 2 metres apart for 30/40 minutes just to get into the shop was pretty stressful for me. I am able to face shops a bit easier now. The friendly faces and chats from the folk delivering these food packages was also so appreciated. Can’t thank them enough.',
    'title' => 'I was having panic attacks',
    'source' => 'Covid Chronicle',
    'storyDate' => '11.6.20',
    'storyDateFormatted' => '2020-06-11',
    'categories' => 'Community sharing, Food insecurity, Cooking, Isolation, Mental health',
    'imported' => '',
  ],
	[
    'author' => 'Denise',
    'story-number' => 12,
    'location' => 'Scottish Borders',
    'text' => 'We were completely unprepared for the absolute avalanche of online sales. We thought it might be as much as we’d get at Christmas, but in the first two or three weeks it was three or four times that amount. We were just knocked sideways. After about the first week, we realised the scale of requirements. We moved from being small-scale specialist artisan producers who nurtured our customers carefully into our ethos, to being thrown onto the front line as key suppliers of food for people in lockdown who couldn’t get access. Our whole attitude has had to change (Soil Association).',
    'title' => 'We were just knocked sideways',
    'source' => 'Covid Chronicle',
    'storyDate' => '17.6.20',
    'storyDateFormatted' => '2020-06-17',
    'categories' => 'Food insecurity, Supply chains, Local economy',
    'imported' => '',
  ],
	[
    'author' => 'Fiona',
    'story-number' => 13,
    'location' => 'West Lothian',
    'text' => 'It has been a dream of ours for some years to have our own vegetable patch. Towards the end of last year we built some raised beds, and placed them in the garden. This year was the first year we have had some crops. I think we chose the perfect year to start a new hobby that’s good for our health and good for the planet. So far, we have grown rhubarb, potatoes, carrots, strawberries, tomatoes, kale, brussel sprouts and lettuce.',
    'title' => 'Good for our health',
    'source' => 'Covid Chronicle',
    'storyDate' => '2.6.20',
    'storyDateFormatted' => '2020-06-02',
    'categories' => 'Seasonal growing, Mental health, Physical health, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Mary',
    'story-number' => 14,
    'location' => 'Edinburgh',
    'text' => 'For me, Covid 19 has woken me up to the importance of my local food system and the civic responsibility I have to and champion it. The small shops and food service businesses who have pivoted so agilely in an attempt to survive and serve their customers have been a real inspiration. They have helped to convert my wished for and thought about behavioural change to actual behavioural change in terms of where I shop, what food and drink I buy, the strength of relationships I have develop with these providers and the pleasure I get from knowing my spending is supporting their businesses, suppliers, staff and families. Prior to Covid 19, the Beach House Cafe (last photo I took pre covid from inside) in Portobello was a nice to visit cafe, since Covid 19 it has become our main grocery shop. One that knows our name, will flex to our diaries and work commitments and who have shown us great care, energy and commitment throughout. They are a shining example of what Covid 19 has thought me. Cherish our local food producers, businesses and organisations as they truly are key workers that deliver so much more than our cupboard basics.',
    'title' => 'Cherish our local food producers',
    'source' => 'Covid Chronicle',
    'storyDate' => '2.7.20',
    'storyDateFormatted' => '2020-07-02',
    'categories' => 'Community sharing, Food insecurity, Supply chains, Worker\'s rights, Local economy',
    'imported' => '',
  ],
	[
    'author' => 'Katharine',
    'story-number' => 15,
    'location' => 'Motherwell',
    'text' => 'Using a local facebook group we reached out to our community members to safely share and exchange plants, whilst carefully keeping to social distancing roles. It\'s so important to remember less formal networks, and the excellent work that has been happening at ground level.',
    'title' => 'Remember less formal networks',
    'source' => 'Covid Chronicle',
    'storyDate' => '30.9.20',
    'storyDateFormatted' => '2020-09-30',
    'categories' => 'Community sharing',
    'imported' => '',
  ],
	[
    'author' => 'Anonymous',
    'story-number' => 16,
    'location' => 'Motherwell',
    'text' => 'On an individual practical/physical level, stress and demands of shopping was exhausting for me as I took on the whole responsibility of food shopping for myself and my husband as I was extremely concerned about protecting, my husband\'s health as he had been very ill with pneumonia last year. I am aware although I look fit, my physical strength and stamina is limited with new hips due to arthritis and joint changes in my hands, I kept my spirits up pre Covid by swimming and meeting people. I found the loneliness and isolation was awful during lockdown and I was extremely low mentally at one point. I have no idea how people in high rise flats coped. I know I am so fortunate to have had the outdoor garden space here, even so mentally I did reach a scarily low point. I worried about what would happen if we had to self isolate and still do, so as I was able I stocked my food cupboard with easily prepared food to keep us going packet soups mainly and UHT milk. Crackers and cheese, eggs if we became ill. Toilet rolls!! Soap powder and I did manage to get paracetamol after about 2 months. My daughter worried about me going out to the shops and purchased food for us and brought it to our back door. It was heart breaking not being able to put my arms round my granddaughter who is an only child. Both of us were desperate to give each other a hug.',
    'title' => 'Loneliness and isolation',
    'source' => 'Covid Chronicle',
    'storyDate' => '7.9.20',
    'storyDateFormatted' => '2020-09-07',
    'categories' => 'Isolation, Mental health, Physical health, Green space',
    'imported' => '',
  ],
	[
    'author' => 'Pat A.',
    'story-number' => 17,
    'location' => 'Gracemount',
    'text' => 'Transition Edinburgh South, have been supporting local families during COVID-19 pandemic at the Gracemount Community Garden - a beautiful space in garden of Gracemount Mansion House in South of Edinburgh. In the garden there are beds of vegetables, fruit, as well as flowers and wild patches. During the pandemic the project received funding from the Scottish Government\'s Wellbeing Fund to organise gardening sessions for 15 families. The families have loved being out in the gardens, with activities like ladybird minibeast hunt as well as focused practical garden activity, such as harvesting, weeding, or sowing. Families would gather fresh produce at the garden session. Great to see that throughout the project there was an increase in number of people visiting the gardens and showing an interest in making use of their local green space.',
    'title' => 'Families have loved being out',
    'source' => 'Covid Chronicle',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Community sharing, Seasonal growing, Mental health, Green space',
    'imported' => '',
  ],
	[
    'author' => 'Sara',
    'story-number' => 18,
    'location' => 'Stirling',
    'text' => 'Stirling is surrounded by farmland – farmland is a 10-minute walk away from anywhere in the city centre, yet despite great need we were unable to source Stirling-grown fruit or vegetables throughout all of lockdown.',
    'title' => 'Unable to source',
    'source' => 'Covid Chronicle',
    'storyDate' => '23.9.20',
    'storyDateFormatted' => '2020-09-23',
    'categories' => 'Local economy, Green space',
    'imported' => '',
  ],
	[
    'author' => 'Anne',
    'story-number' => 19,
    'location' => 'Craigsbank',
    'text' => 'There has been no logic, no common sense to the distribution of free school meals, with families getting meals every week with yoghurt despite children being lactose intolerant and families have to go and pick-up the meals from school and the bags are all labelled with names clearly identifying which children are entitled to free school meals.',
    'title' => 'No logic, no common',
    'source' => 'Covid Chronicle',
    'storyDate' => '2.9.20',
    'storyDateFormatted' => '2020-09-02',
    'categories' => 'Food insecurity, Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Joe',
    'story-number' => 20,
    'location' => 'Glasgow',
    'text' => 'The amount of people we were supporting in a relatively small area of Glasgow tripled. We went from support about 50 to 80 people to having support 250 to about 300 people at the peak. And that was through weekly food parcels… And this is just a very small part of Glasgow I\'m talking about. So you\'re talking about 300 people were needing emergency food support to stop them going hungry every single week. And when you extrapolate that for the whole city, I have no idea what the figures are. But I was I was gobsmacked by the need that kind of came out with COVID. I think what we saw that was causing the need, was a number of things that were really exacerbated by COVID.',
    'title' => 'I was gobsmacked',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Community sharing, Food insecurity, Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Joy',
    'story-number' => 21,
    'location' => 'Dalkeith',
    'text' => 'The Community Council decided that a hot food delivery project was what was needed, because there was some people isolating and some people in poverty… it meant a lot in terms of the personal touch and the emotional value - that someone\'s cared for me to provide this. So it was sort of a different service than the food parcels which was ran by another organisation. But it was a really good insight into, what would a resilient community look like if people need that service? How do we get that food to them in an efficient way? And I think that the local provision came from somebody whose business was under threat, because of losing business because of the lockdown. So, she was able to help out. And I think that sometimes very local provision is better value than some of the big companies that councils signed contracts with, and people can\'t afford those. So is it just shows how and local knowledge and skills and really contribute to community being brought together like that. So, I found I found that in that that whole situation was really interesting.',
    'title' => 'Someone\'s cared for me',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Community sharing, Cooking, Local economy, Mental health',
    'imported' => '',
  ],
	[
    'author' => 'Stuart',
    'story-number' => 22,
    'location' => 'Edinburgh',
    'text' => 'What I find in lockdown is I\'ve been stuck at home the whole time. You\'re working from home, my wife\'s working from home. And it\'s been very advantageous because although you\'re working from home, you are also sort of being able to do stuff in the garden. What I found is that we\'ve actually had the perfect storm this year for home growing. Because, you know, we saw the lockdown come in, we thought, well, there\'s going to be problems with food. But we thought let\'s just go for it in the garden, let\'s just see how much we can grow from our garden, we\'ve got your bog standard sort of semi detached tires, the bit in front, the bit in the back. So we basically put down food everywhere. And, you know, it\'s just of all went very well. And, in fact, it went too well, because we seem to have the perfect mix of rain, sun, no real pests this year. And so far, I haven\'t bought any fruit or veg since June. I\'ve eaten more potatoes than I think I\'ve ever eaten in a couple of months. I think we\'ve got enough potatoes until March… supermarkets just really aren\'t a thing for me now.',
    'title' => 'Go for it in the garden',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Mary #2',
    'story-number' => 23,
    'location' => 'Edinburgh',
    'text' => 'I knew I wanted to buy more locally… and this has sort of driven us to that. It really transformed my relationship to that local food system and there\'s a whole range of other small businesses that have been brought through to me, or made it really easy for me to go and get food from them…  I think it\'s transformed what I know about my local community. I think it\'s made me more grounded within my local community. It\'s made me more respectful and aware of the key workers and that in the in the broadest sense of the word. And it\'s introduced us to some great small producers and small brands.',
    'title' => 'Made me more respectful',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Worker\'s rights, Local economy',
    'imported' => '',
  ],
	[
    'author' => 'Rachel',
    'story-number' => 24,
    'location' => 'Inverness',
    'text' => 'We\'ve been trying to highlight to folk for the last three years that our food system in Scotland in the UK is incredibly precarious. And it\'s only like, one crisis away from people we know, not having food. And what COVID actually did was create a cold, hard reality for people with that. So we found that we didn\'t have to try and convince people anymore, they believed us. And so the usage of our community fridge shot up, we went from an average of about 63 kilogrammes of food a month went up to 500 kilogrammes of food. What was really interesting was that, as well as the usage of the community fridge going up, the supermarkets were also donating way more food to the fridge as well, because actually, they had a whole load of surplus food, there was other stuff that people weren\'t buying apart from pasta and bread or whatever, there was a whole load of other food, which they were over supplying, there was way too much. So that came funnelled into our community fridge. And it would go within half an hour, like we would fill the fridge and it would be gone.',
    'title' => 'Incredibly precarious',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Community sharing, Food insecurity, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Patterson',
    'story-number' => 25,
    'location' => 'Buchan',
    'text' => 'I live on my parents farm. And we do sustainable wool. And it\'s something I\'m really passionate about. But then COVID happens and obviously disrupted food chains everywhere. And I\'m half Australian. So I saw the difference between my family in Australia, and their access to food, the food chain in Queensland compared to rural Aberdeenshire. And it kind of made me think that probably someone like me, should be making more food for the local area. And it\'s really been trying to just start out with eggs, you know, and grow my own veg. I tried to work out from there how to feed a local area.',
    'title' => 'Disrupted food chains everywhere',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Food insecurity, Supply chains, Local economy, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Izzy',
    'story-number' => 26,
    'location' => 'Glasgow',
    'text' => 'In the east end of Glasgow, the initiative that we started with 20 people got to 3000 a week. And the amount of people that were very vulnerable that we unearthed that hadn\'t eaten nothing from one day to the next. But they didn\'t have the methods of communication to get it out. There was no social work involvement. They weren’t neighbourly per se, but they were sitting just on their own and it was heart-breaking, especially the elderly - a lot of a generation that just won\'t ask for help. And it was really quite upsetting at times.',
    'title' => 'It was heart-breaking',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Food insecurity, Isolation, Mental health',
    'imported' => '',
  ],
	[
    'author' => 'Dan',
    'story-number' => 27,
    'location' => 'Glasgow',
    'text' => 'What the pandemic has also shown is that it\'s just exposed what a lot of people already knew about the welfare system and about how sort of ridiculous these seen off people on lower incomes and no incomes are and I think that a lot people already knew that - I think that to the broader general public, it\'s become a lot more clear. And I think that a great example of that sort of inequality is the sort of the vouchers, the meal vouchers that kids were getting the amount into sort of think, like 15 pound a week, or I think, yeah, and like he out help out the saving middle class families, like hundreds of hundreds of pounds a week on their meals at the outlet. I think that\'s, I don\'t think that\'s gone completely amiss for folks. I think people have flocked onto that. But I think it\'s just exposed how unequal our society already is.',
    'title' => 'Exposed how unequal',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Food insecurity, Inequality',
    'imported' => '',
  ],
	[
    'author' => 'Wendy',
    'story-number' => 28,
    'location' => 'Aberdour',
    'text' => 'One of the things that also has spurred me on this month is foraging free foods, because whilst I’m a long way from the food banks, fortunately, I certainly still need to count my pennies, as many of us I\'m sure are. And, and there\'s so much free food out there, and it\'s a thing that people have got out of the habit of foraging. So, it\'s good for our wellbeing as well as getting some goodies.',
    'title' => 'The habit of foraging',
    'source' => 'Food Stories Workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Seasonal growing, Green space',
    'imported' => '',
  ],
	[
    'author' => 'Emma',
    'story-number' => 29,
    'location' => 'Muir of Ord',
    'text' => 'One of the jobs that I do is, I\'m the founder and manager of a food community charity called Moo Food up in the Highlands. And we sort of switched our role during COVID. What we do is we\'ve got an edible village, with orchards and growing boxes and it’s filled with food all year to try and give people in the village access to seasonal food. And we\'ve also got a community fridge at the heart of that for as a platform for sharing surplus food. We changed it during lockdown to start providing emergency food parcels and this is sort of stuck with me - the heart ache that brought. The budget that I found myself having to buy scores of people food was the same amount of budget I had for the month to feed five people. I knew I was in a very fortunate position in life that I can afford to feed myself and my family good food. But it sort of brought it home. The reality that what I was using one small budget to feed five people, I was using that to feed scores of people. And that was that\'s been emotionally really quite difficult… it\'s really, really heart-breaking. Also with these emergency food parcels, there was a mad sort of burst of demand in March and April, and it sort of balanced off and died down. But then there\'s still lots of people that are still coming twice a week to get emergency food parcels. And it\'s not because of COVID that they\'re there, it’s this wider chronic situation and people were in need of these parcels long before in COVID.',
    'title' => 'Emotionally really quite difficult',
    'source' => 'Food Stories workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Community sharing, Food insecurity, Seasonal growing, Green space, Inequality, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'John',
    'story-number' => 30,
    'location' => 'Glen Etive',
    'text' => 'I live in the country, I work part time in a care home. The biggest thing I\'ve seen during this lockdown is people divided very, very quickly. Where I live, they don\'t want other people to come in to the countryside, which I think it\'s highly, highly dangerous the way things are going. At the end of the day, we\'ve all got to share things, and people don\'t want to share. I\'ve seen people being very great. But I\'ve seen the other side of people changing really, really quickly.  I think a lot of people don\'t realise where I live, generations have been coming here. And even though they don\'t live here, they are connected here to the generations from bringing their children children to here… I\'ve seen not a good sight to people.',
    'title' => 'People divided quickly',
    'source' => 'Food Stories workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Isolation',
    'imported' => '',
  ],
	[
    'author' => 'Gail',
    'story-number' => 31,
    'location' => 'Inverness',
    'text' => 'Some communities have come together more to help each other, especially around food, perhaps shopping for neighbours, sourcing local food, or advising others where they\'re getting their milk delivered from and this sort of thing. So, I don\'t think it\'s all bad in fact, people couldn\'t really travel around. So, we were forced to just be in that five mile radius and kind of identify with that sort of idea and what\'s there or who was there? I think from my point of view, it\'s actually quite good because I was able to grow things in my own garden and perhaps, seeds from some other people to sort of share around. And as far as sort of growing personally, I\'ve improved.',
    'title' => 'Communities have come together',
    'source' => 'Food Stories workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Community sharing, Local economy, Seasonal growing, Green space',
    'imported' => '',
  ],
	[
    'author' => 'Liz',
    'story-number' => 32,
    'location' => 'Edinburgh',
    'text' => 'I think in my locality people in general have been very helpful towards each other. And we\'ve got to know neighbours we didn\'t know before, especially when we were clapping for the NHS. And, you know, that brought about a sense of community. And as far as our local group is concerned, we\'re trying to liaise with the council to plant apple trees in areas of east Craigs, which we hope will be of use to the community and maybe expanded on – I’ve been reading a lot about urban growing.',
    'title' => 'Sense of community',
    'source' => 'Food Stories workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Community sharing, Seasonal growing, Green space',
    'imported' => '',
  ],
	[
    'author' => 'Andrew',
    'story-number' => 33,
    'location' => 'Edinburgh',
    'text' => 'I was a bit more conscious about what food I was buying. But I realised that during the height of lockdown with the restrictions on things we couldn’t do, how much a role food played in comfort and providing entertainment - a thing to do in the evening after work with trying new recipes. And it is a privilege to experiment, but for those that can I think food can play such a vital role in your mental health and in trying new foods and pushing boundaries with what you wouldn\'t eat before.',
    'title' => 'Vital role in your mental health',
    'source' => 'Food Stories workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Mental health',
    'imported' => '',
  ],
	[
    'author' => 'Stephanie',
    'story-number' => 34,
    'location' => 'Edinburgh',
    'text' => 'I think it\'s a shame because my sense was that there seems to be a bigger consumer push towards moving away from plastics recently, especially when it comes to food packaging and the consumer, the mentality in supermarkets seem to be paying more attention to that as well. But now with what\'s happened with COVID, the use of plastic, it\'s just shot up again. It just feels like it\'s not priority to people, they keep thinking about, "well, this is exceptional circumstances". But of course, the more that it just becomes greater plastic, greater packaging, cleanliness sort of concerns around that and everything is disposable - the masks and everything that\'s involved there. It\'s such a shame because it exists in this contradiction with people being more aware of nature as well and people reflecting upon “oh, gosh, there\'s been less cars. It\'s lovely to see that there\'s actually birds, who knew there were birds around” and this sort of thing. So, it\'s real shame to have that contradiction that Covid’s brought out quite a bit',
    'title' => 'Contradiction that Covid’s brought out',
    'source' => 'Food Stories workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Supply chains, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Pat S.',
    'story-number' => 35,
    'location' => 'Dunblane',
    'text' => 'I coordinate the Intergenerational National Network. And one of the things that I feel very strongly about is that one of the most powerful ways of bringing people together across generations, is food. And so, I suppose in a sense, this is almost a bad story rather than a good one. Because obviously, that is one of the things we just have not been able to do… I don\'t know if people are familiar with the work of the Citadel in Leith. But they do a load of really, really wonderful stuff. And one of the things they do, they do an intergenerational project called new spin, which brings people together on a Friday afternoon and people across generations, primarily young people and older people, but very much open to anybody. And what they do, they eat together, they eat and run tables. So there\'s no sort of sitting in your own little group. And then they do activities together. And it\'s been going for 10 years now. And it is just amazing. And they always make too many seedlings, they always make far too much too deliberately so that everybody takes food away from the weekend as well. You know, and it is about that, you know, everybody takes it away from the weekend, doesn\'t matter whether you\'re in need or not. And of course, that just hasn\'t been possible during Covid which is quite frustrating.',
    'title' => 'Brings people together',
    'source' => 'Food Stories workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Community sharing, Isolation, Mental health',
    'imported' => '',
  ],
	[
    'author' => 'Irina',
    'story-number' => 36,
    'location' => 'Edinburgh',
    'text' => 'I think the right to food now has become a priority after COVID and the current circumstances, the challenges that organisations that we work with are facing and will be facing. I think it\'s time for us to stand up and really do something about it and I think … everybody has some kind of issue about food. And as you said, Lewis, you know if you eat you\'re in and we are all in so what we have to do I think is raise awareness about this and get people to care. How to communicate, how to engage more people in these conversations, how local authorities should be involved in these conversations - they should be listening to the people that are working around food,  around communities… the right word means so much, personally, and to the many communities that we work with.',
    'title' => 'Time for us to stand up',
    'source' => 'Food Stories workshop 1',
    'storyDate' => '26.8.20',
    'storyDateFormatted' => '2020-08-26',
    'categories' => 'Right to food',
    'imported' => '',
  ],
	[
    'author' => 'Jo',
    'story-number' => 37,
    'location' => 'Dunbar',
    'text' => 'So for me, the thing that that\'s kind of interesting about food is what we\'re trying to do is to kind of build resilience in the community. So that\'s one by kind of looking at all of the issues across the board that this that this kind of, you know, good food is embedded in there. And it tackles, as we say, sort of everybody\'s got, what he\'s got to connect with food, you know, if you eat you\'re in. And so it seems that it\'s a really useful tool to kind of take out there as a way of engaging with people, and getting more people to kind of be involved in different aspects of, you know, what\'s happening in their community or what isn\'t happening and trying to make that happen. So, yeah, that\'s the journey we\'re on.',
    'title' => 'Build resilience in the community',
    'source' => 'Food Stories workshop 1',
    'storyDate' => '26.8.20',
    'storyDateFormatted' => '2020-08-26',
    'categories' => 'Community sharing, Right to food',
    'imported' => '',
  ],
	[
    'author' => 'Izzy #2',
    'story-number' => 38,
    'location' => 'Glasgow',
    'text' => 'Everyone should have a right to food, regardless of background. And the difficulty is in finding the people who are too proud to come in ask (for help). And it\'s providing food with dignity. What I\'d love to see in an ideal world, is that everyone knows where to go to get help. And the government has to accept responsibility and do it properly, and engage with people who are on the ground to know what\'s happening, and not just sit somewhere in an office and try and control it from there, you know, go out speak to the people that are dealing with this day in and day out and manage your programme based on that, rather than paper reading exercises or tickbox exercises.',
    'title' => 'Providing food with dignity',
    'source' => 'Food Stories workshop 1',
    'storyDate' => '26.8.20',
    'storyDateFormatted' => '2020-08-26',
    'categories' => 'Food insecurity, Right to food',
    'imported' => '',
  ],
	[
    'author' => 'Kirsten',
    'story-number' => 39,
    'location' => 'Edinburgh',
    'text' => 'It’s interesting to hear about some of the work that was happening around the engagement of different socio-economic background Scotland. The whole good food agenda has, to a certain extent been accused of being a very middle class thing. And where the representative cross section of Scottish voices is not necessarily being involved in the debate. And, and there\'s a second thing, which is you can provide food, good food, but will people necessarily engage with it? And by people, I mean, everybody. So there\'s, there\'s quite a lot of variables here, in terms of who defines what food is, you know, my concept of food of someone from the far north of Scotland, is very likely to be very different to what\'s happening in an urban context, and even some parts of Edinburgh or Glasgow. So it\'s more than just this this sort of, I suppose, concept of the right to food. There\'s quite a lot of bigger issues around it.',
    'title' => 'Who defines what food is',
    'source' => 'Food Stories workshop 1',
    'storyDate' => '26.8.20',
    'storyDateFormatted' => '2020-08-26',
    'categories' => 'Local economy, Inequality, Right to food',
    'imported' => '',
  ],
	[
    'author' => 'Kirsten',
    'story-number' => 40,
    'location' => 'Edinburgh',
    'text' => 'It’s important to help people to understand that good food is this tree off of sustainability, in terms of, you know, ecology, health, and, and social. Doing that in a way that that that really engages people with where food comes from, you know, it\'s only a generation since we really lost our connection to all of this. And perhaps, you know, that that idea of giving ownership back to some of the indigenous food cultures across Scotland, so, but it’s this idea of good food not being seen as something elitist, and I\'m making that very explicit in a right to food strategy, that it\'s right to good food. You made the point about junk food and that is a danger that, you know, as we slip into what looks increasingly like a no-deal Brexit, any food is going to be what people are aspiring to. So, saying from the off that it\'s not just about the right to food rate or having a full belly – it’s good food. We\'re saying we explicitly that it\'s a good food nation, it\'s a good food nation Bill.',
    'title' => 'Giving ownership back',
    'source' => 'Food Stories workshop 1',
    'storyDate' => '26.8.20',
    'storyDateFormatted' => '2020-08-26',
    'categories' => 'Physical health, Environmental concerns, Right to food',
    'imported' => '',
  ],
	[
    'author' => 'Chris',
    'story-number' => 41,
    'location' => 'Edinburgh',
    'text' => 'Edinburgh Community Food quickly adapted to the pandemic, becoming a core member of the Vulnerable Group Food Network, supplying up to 1200 weekly large boxes of fresh food, long-life items and nutrition info to households. Thanks to pre-existing supply chains we could source most items with relative ease. However, there were notable shortages and crippling limits imposed on certain items. We are highly anxious about how our communities will cope going forward, with a mooted world food shortage, a \'second wave\' and the winter flu season. We\'ve developed new and demonstrably effective ways of linking with our communities online and feedback has been humbling and inspiring.',
    'title' => 'We are highly anxious',
    'source' => 'Covid Chronicle',
    'storyDate' => '28.8.20',
    'storyDateFormatted' => '2020-08-28',
    'categories' => 'Community sharing, Food insecurity, Supply chains',
    'imported' => '',
  ],
	[
    'author' => 'Brenda',
    'story-number' => 42,
    'location' => 'Edinburgh',
    'text' => 'Edinburgh Community Food’s work has previously focused on food insecurity, but not from the crisis end. However, due to Covid-19, that changed overnight. In a decent society it is not acceptable what’s happening with food right now. We need colour and breadth of food choices to inspire children. People need to have the money to have food disasters! Food brings us together. We upheld our dignity and values throughout our Covid-19 response work, where we bought fresh fruit and veg to give to people. This really transforms their food experience and the quality of what they get. Meals in a bag and food from different cuisines really got people engaged with cooking and eating. It’s key to keep in mind that when parachuting food in and helping people in crisis, they can become reliant, and struggle when an organisation pulls out. For people with dependency issues, choices around food can therefore be very important. Throughout lockdown we also undertook a BME survey focusing on food choices, enabling them to provide tailored, culturally appropriate boxes. We must all recognise the social value of food.',
    'title' => 'It is not acceptable',
    'source' => 'Covid Chronicle',
    'storyDate' => '5.10.20',
    'storyDateFormatted' => '2020-10-05',
    'categories' => 'Community sharing, Food insecurity, Inequality',
    'imported' => '',
  ],
	[
    'author' => 'Karen',
    'story-number' => 43,
    'location' => 'Rosyth',
    'text' => 'I have enjoyed building a community around food in Rosyth for the last few years, accessible to everyone, based on fun, learning and sharing. It is disheartening to see that work had to turn into emergency food aid during Covid, a sign of a broken food system. The system should ensure food is accessible to all and allow the energies of food workers to go into building food literacy, growing local supply chains and community wellbeing instead of purely food provision.',
    'title' => 'Sign of a broken food system',
    'source' => 'Covid Chronicle',
    'storyDate' => '15.10.20',
    'storyDateFormatted' => '2020-10-15',
    'categories' => 'Community sharing, Food insecurity',
    'imported' => '',
  ],
	[
    'author' => 'Anonymous',
    'story-number' => 44,
    'location' => 'Dunfermline',
    'text' => 'Using companies on our own doorstep for produce deliveries allowed us to support local businesses and keep our family safe during the early uncertain times of lockdown.',
    'title' => 'On our own doorstep',
    'source' => 'Covid Chronicle',
    'storyDate' => '15.10.20',
    'storyDateFormatted' => '2020-10-15',
    'categories' => 'Local economy',
    'imported' => '',
  ],
	[
    'author' => 'Roz',
    'story-number' => 45,
    'location' => '',
    'text' => 'March 2020 saw an unprecedented increase in demand for food in the UK, with supermarket shelves lying empty, and rationing systems set up for some essential items. This was not just an inconvenience in our usually convenient system. People lost their jobs and homes overnight and were forced to food banks, with food bank usage nearly doubling in comparison to 2019. Supply from supermarkets to food banks dropped as more food was being sold in store, pushing some food banks to close. At the same time, as much as £20million of fresh food destined for hospitality and schools was at risk of being dumped, and thousands of litres of milk were poured down the drain as dairy farmers lost their markets. For many people, our supply chains broke down, exposing the weaknesses in the global, just-in-time system. As is so often the case, farms were left with little support or security as prices and demand fluctuated. Covid-19 is not the last crisis we will see over the next few years. The climate crisis is now widely recognised as one of the biggest, if not the single biggest threat to food security. We need to act quickly to transform our food system to one that is more resilient, creates decent livelihoods for producers, and is based on principles of agroecology and food sovereignty. Direct sales systems offer one tool to help build the food system that we urgently need.',
    'title' => 'Farms were left with little support',
    'source' => 'SFC Blog',
    'storyDate' => '16.10.20',
    'storyDateFormatted' => '2020-10-16',
    'categories' => 'Supply chains, Worker\'s rights, Inequality, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Tilly',
    'story-number' => 46,
    'location' => 'Edinburgh',
    'text' => 'Covid-19 and its impact should be a wake-up call. The term ‘build back better’ has been coined as a phrase in the recovery phase of Covid-19. We must centralise this approach and use this opportunity to reshape our future food system and not return to a normality, that includes unacceptable levels of food insecurity, social isolation and malnutrition, amongst older people. Centralising the social value of food and recognising it’s direct connection to social risk-factors and link to wider health priorities, is key, if we are to ‘build back better’ and create a Scotland that prioritises “ensuring people are healthy, happy and secure in older age” and in the process ensure the preventable issues of malnutrition and social isolation are not prolific to the ageing experience in Scotland. Moving forward, cross-sectoral reflection and ‘joined-up’ conversation, learning, and action is key. The Covid-19 response has emphasised how crucial community-based solutions are; and how grassroot investment can result in an effective, individualised response, that understands its community. If we are to deliver radical change that recognises that- food is a tool, food is a connector and food is social, community, grassroots approaches and the third sector must be at the heart of this.',
    'title' => 'Food is a connector',
    'source' => 'SFC Blog',
    'storyDate' => '26.6.20',
    'storyDateFormatted' => '2020-06-26',
    'categories' => 'Isolation, Mental health, Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Kirsty',
    'story-number' => 47,
    'location' => 'Edinburgh',
    'text' => 'There are links between the now infamous wildlife markets and coronavirus. Perhaps less known is the global link between both of these and intensive farming, which has pushed small farmers out of farming domestic species and into catching or breeding wild animals, and has consumed ever more land, colonising the spaces inhabited by wild animals, and allowing easy disease transfer between these worlds. Covid-19 is the latest but by no means the only disease linked to intensive animal farming. Intensive farming creates conditions which allow diseases to thrive: overcrowding and compromised immune systems due to stress. The industry response is to routinely use antibiotics as a preventative measure, contributing greatly to the growing antimicrobial resistance which threatens the foundations of our healthcare repository, with potentially catastrophic results. As explorer and naturalist John Muir said, “When we try to pick out anything by itself, we find it hitched to everything else in the Universe.” It is time to lose the anthropocentric notion that we can set ourselves above and apart from all other beings, and predict or control the outcomes of our actions. Every animal whose life is touched by these scenarios was put in that position by humans. Thus, it is just as unfair and illogical to blame coronavirus on bats as it is to blame pigs for chewing off each others’ tails, as a consequence of their constricted existence.',
    'title' => 'Threatens the foundations',
    'source' => 'SFC Blog',
    'storyDate' => '21.5.20',
    'storyDateFormatted' => '2020-05-21',
    'categories' => 'Physical health, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Anna',
    'story-number' => 48,
    'location' => 'Glasgow',
    'text' => 'Covid-19 is a highly contagious disease that has caused the deaths of tens of thousands of people in the UK since its outbreak. Governments around the world advised people to stay at home to stop the spread of the disease. As a result, our lifestyles have dramatically changed. This one single health problem, in a very short time, affected not only everyday lives, but also politics, industry, trade and the economy. The COVID-19 crisis has shown in a cruel way how important health is. We need a food system that provides food that is nutritious and healthy. The COVID-19 crisis couldn’t have highlighted this need more. The response to COVID-19 must include actions to help people in Scotland eat healthier diets. Healthy diet is key for improving immunity, therefore action to support that would increase resilience to COVID-19 and other communicable diseases. It would also help to address diet-related non-communicable diseases, such as cardiovascular disease or diabetes, that are so prevalent in Scotland.',
    'title' => 'Healthy diet is key',
    'source' => 'SFC Blog',
    'storyDate' => '4.6.20',
    'storyDateFormatted' => '2020-06-04',
    'categories' => 'Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Martin',
    'story-number' => 49,
    'location' => 'Shetland',
    'text' => 'We tried to diversify and see what the needs of the people and the community was, and just changed how we sold fish to make it more accessible to people that was self-isolated and that type of thing. I think if we hadn’t changed anything and just carried on selling the fish the way we were before lockdown, we wouldn’t have been very busy at all. But we’ve actually been busier from the lockdown started, doing deliveries and people coming to pick up fish and that type of thing. A lot of the people now in Shetland are trying to source local produce, whether it’s fish, or beef, or eggs, vegetables, anything—try and get it locally if they can… which is good for the local economy too (Farmerama Radio).',
    'title' => 'We’ve actually been busier',
    'source' => 'Farmerama',
    'storyDate' => '19.10.20',
    'storyDateFormatted' => '2020-10-19',
    'categories' => 'Supply chains, Local economy',
    'imported' => '',
  ],
	[
    'author' => 'Isobel',
    'story-number' => 50,
    'location' => 'Edinburgh',
    'text' => 'I think when you turn up at the supermarket, and there are things just not available like flour, and a lot of people are doing baking at the moment, it does make you kind of think twice about where that\'s come from and who\'s produced it and what impact that\'s had really on nature as well as people, like what jobs has that created. Another issue… is food waste. I think when you\'re eating three meals a day at home, you\'re a lot more aware of what you\'re chucking in the bin. And, you know, the first couple of weeks we weren\'t quite getting it right, like the amount of fresh food we were buying versus the amount of dry food and stuff. So we ended up maybe wasting a bit more than I wanted. And so we\'ve changed our habits a bit to make sure we\'re not doing that as much and like coming up with creative ways to use up odds and ends. I\'d say my three key takeaways from all of this have been that I want to limit my food waste as much as I possibly can, support local businesses as much as they can and get food from places that it\'s grown in a way that\'s good for climate and nature.',
    'title' => 'Good for climate and nature',
    'source' => 'Covid Chronicle',
    'storyDate' => '25.5.20',
    'storyDateFormatted' => '2020-05-25',
    'categories' => 'Supply chains, Worker\'s rights, Local economy, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Knockfarrel Produce',
    'story-number' => 51,
    'location' => 'Knockfarrel, Dingwall',
    'text' => 'The Covid-19 pandemic is changing the balance of our business: box scheme demand rose sharply during lockdown, and we took on an extra 30% of subscribers, mostly older people who were shielding. We also had to turn away many potential customers who we were simply unable to serve. Most of the new customers have stuck with us, and spend per customer across all the boxes is up 20% too. But we have had no farmers’ markets. Overall the increased veg box income has almost equalled the lost market revenue. If Covid-19 continues into another year, we may sell solely through the box scheme - the only real downside of this is that veg box customers buy about 75% veg and 25% value added produce from us; whereas market customers buy less veg and more higher value products. To survive on veg sales alone we will need to rent land and plant more; or we can look for alternative markets for our processed foods. We also had staff shortages during lockdown, as our overseas trainees booked to work with us for the season could not travel. Instead we have taken on and trained two new local people – this is good to do, but they are not getting the formal educational back up they need, as there are no Scottish higher education institutions offering horticultural or local food training to them (LWA September 2020).',
    'title' => 'Changing the balance of our business',
    'source' => 'Land Workers\' Alliance',
    'storyDate' => '1.9.20',
    'storyDateFormatted' => '2020-09-01',
    'categories' => 'Supply chains, Worker\'s rights, Local economy, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Appletreeman',
    'story-number' => 52,
    'location' => 'Spittalfield, Perthshire',
    'text' => 'Currently, and despite Covid-19 and lack of outdoor markets, we have many customers already looking ahead to the winter sales. However, there’s likely to be a significant drop in sales to community orchard projects due to lack of funding and ability for community projects to run. As a result I’m potting on quite a lot of trees for sale next year (LWA September 2020).',
    'title' => 'Drop in sales',
    'source' => 'Land Workers\' Alliance',
    'storyDate' => '1.9.20',
    'storyDateFormatted' => '2020-09-01',
    'categories' => 'Local economy, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Tomnah’a Market Garden',
    'story-number' => 53,
    'location' => 'Comrie',
    'text' => 'The biggest blow is the lack of weddings which is a fair chunk of our income and we can’t see these getting back to normal in the near future. Luckily being a small diverse business means we are able to change and adapt quite easily and these lack of sales gave us more time to look at the wider flower market and how we can work together to reduce the use of imported flowers. The lack of restaurant and other wholesale was a worry as this is important to our business but it coincided with a rise in the use of online food hubs which we were selling to around 200 customers during the busiest time through 3 different hubs. We are looking at setting up a food hub here at Comrie Croft as the farmshop here has really suffered from Covid-19 having to close down for two months and now being short staffed. We hope pre-ordered sales will mean the shop can offer more variety especially of perishable items (like our own) and will be less risky for buying things in. We were also supported by our local baker who quickly had to change their wholesale business to doorstop retail and hubs and we were able to offer salad, other greens and cut flowers alongside their bread which is delivered across the central belt. It was great to see another business react to quickly and positively to the situation and join forces (LWA September 2020).',
    'title' => 'Join forces',
    'source' => 'Land Workers\' Alliance',
    'storyDate' => '1.9.20',
    'storyDateFormatted' => '2020-09-01',
    'categories' => 'Community sharing, Supply chains, Local economy, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Whitmuir the Organic Place',
    'story-number' => 54,
    'location' => 'West Linton',
    'text' => 'When lockdown was announced the Whitmuir shop and café closed to walk-in customers. The shop was not an essential service especially as people had to drive to get there - and the risk to staff was significant, especially for those staff living with people who were at particular risk from the disease. The business moved online and for a few weeks experienced a huge surge in demand along with supply chain shortages, delivery challenges and a key member of staff being away. Many new customers offered to become farm supporters as a way to secure a delivery and were told that this wasn’t necessary. As supplies and shops returned to nearer normal, many customers fell away, and deliveries went back to around twice their pre Covid-19 level (LWA September 2020).',
    'title' => 'Huge surge in demand',
    'source' => 'Land Workers\' Alliance',
    'storyDate' => '1.9.20',
    'storyDateFormatted' => '2020-09-01',
    'categories' => 'Supply chains, Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Caroline #1',
    'story-number' => 55,
    'location' => 'Glasgow',
    'text' => 'I went to Aberdeenshire in April to care for my mum who was dying of cancer, it was during lockdown. I spent two weeks trying to get shielding boxes for us. I had no one to take me to nearest town six miles away for essentials and could not leave my mum on her own. I was eventually contacted the day she died saying we could get one…no agency was there to help us.',
    'title' => 'No agency was there to help us',
    'source' => 'Covid Chronicle',
    'storyDate' => '31.10.20',
    'storyDateFormatted' => '2020-10-31',
    'categories' => 'Food insecurity, Isolation, Mental health, Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Caroline #2',
    'story-number' => 56,
    'location' => 'Glasgow',
    'text' => 'Covid has again led to having to make the choice between heating and eating due to enforced being at home during the pandemic. When I do it’s junk food due to rising costs of healthy foods… cheaper to buy a bag of frozen chips than fresh potatoes.',
    'title' => 'Choice between heating and eating',
    'source' => 'Covid Chronicle',
    'storyDate' => '31.10.20',
    'storyDateFormatted' => '2020-10-31',
    'categories' => 'Food insecurity, Physical health, Inequality',
    'imported' => '',
  ],
	[
    'author' => 'Anonymous',
    'story-number' => 57,
    'location' => 'Culbokie, Dingwall',
    'text' => 'We grow lots of our own fruit and veg, but we\'re also lucky to have a weekly market in the village with fish, venison, eggs, pork and other goodies. We bake our own bread - I have a bee in my bonnet about the use of glyphosate to dry cereals, so we use organic flour. And talking of bees we also have 2 hives which give us honey.',
    'title' => 'Bee in my bonnet',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '24.10.20',
    'storyDateFormatted' => '2020-10-24',
    'categories' => 'Local economy, Seasonal growing, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Anonymous',
    'story-number' => 58,
    'location' => 'Dingwall',
    'text' => 'We live in Dingwall and my parents have a Croft, so we have our own eggs, venison & fish. We do try to be very good and shop local where we can instead of supermarkets. We make lots of jams with home grown fruits & my mum does loads of baking and cooking, always from scratch with ingredients bought locally or home grown. The veggies, we buy just now from The Spud Bus - love supporting local farmers and it’s our small way of showing appreciation.',
    'title' => 'Love supporting local farmers',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '10.10.20',
    'storyDateFormatted' => '2020-10-10',
    'categories' => 'Cooking, Local economy, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Nikky',
    'story-number' => 59,
    'location' => 'Strathpeffer',
    'text' => 'I bake organic bread from home as Strathpeffer Artisan Bread. We bake a range of breads including sourdough and deliver locally to our customers. We love baking bread because there is so little waste, we either reuse our paper flour bags or compost them in the garden!',
    'title' => 'So little waste',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '12.10.20',
    'storyDateFormatted' => '2020-10-12',
    'categories' => 'Cooking, Local economy, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Aimee',
    'story-number' => 60,
    'location' => 'Scatwell House, Muir of Ord',
    'text' => 'I started growing veg in a walled garden for the first time this year. I feel like I had more failures than successes but it was a huge amount of fun and I learned lots. The most important thing I learned is you have to get the nutrients in your soil right. I am super excited about next year.',
    'title' => 'Super excited about next year',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '9.10.20',
    'storyDateFormatted' => '2020-10-09',
    'categories' => 'Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Lynsey',
    'story-number' => 61,
    'location' => 'Tower Farm, Muir of Ord',
    'text' => 'We source our fruit, vegetables and eggs at Black Isle Berries at Tore. We have a garden full of apple and plum trees as well as berries. We tried growing vegetables this year and have winter veg growing. The only red meat we eat is local venison. We are trying really hard to not shop at supermarkets and support local producers. I also run a zero waste market which promotes local produce and plastic free shopping',
    'title' => 'Support local producers',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '9.10.20',
    'storyDateFormatted' => '2020-10-09',
    'categories' => 'Local economy, Seasonal growing, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Clive and Julie (Black Isle Permaculture & Arts)',
    'story-number' => 62,
    'location' => 'Black Isle, Muir of Ord',
    'text' => 'We are Black Isle Permaculture & Arts (BIPA), an ecological household, garden and woodland on the Black Isle, 13km north of Inverness in the Highlands of Scotland. We offer off grid tourist accommodation, courses, workshops and volunteering opportunities covering a variety of topics focused on sustainable and regenerative living, such as forest gardening, organic food growing and preserving. The household and gardens are being transformed using Permaculture design and techniques to create a balanced ecosystem for people, plants and animals while also adapting to the unfolding climate and ecological crisis. On the 2.5 acre garden and woodland, we aim to live a creative, sustainable and resilient lifestyle by the three simple principles of People Care, Earth Care and Future Care: a place where people can visit, stay, learn and share.',
    'title' => 'A balanced ecosystem',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '9.10.20',
    'storyDateFormatted' => '2020-10-09',
    'categories' => 'Seasonal growing, Green space, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Rebecca',
    'story-number' => 63,
    'location' => 'Muir of Ord',
    'text' => 'My food story is about eating organic and locally sourced food as much as you can. We use a local organic supplier Knockfarrel Produce who deliver a great variety of veg, eggs, cheese and pork. Over the last couple of years I have got into fermenting food which is a great way to preserve some of the organic veg... I have fermenting chillies and garlic on the go at the moment ready to make my own spicy sauce.',
    'title' => 'Eating organic and locally',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '9.10.20',
    'storyDateFormatted' => '2020-10-09',
    'categories' => 'Cooking, Local economy',
    'imported' => '',
  ],
	[
    'author' => 'Lynsey',
    'story-number' => 64,
    'location' => 'Muir of Ord',
    'text' => 'I love the idea of the Highland Good Food Conversation and think it\'s an important one to be having especially at the moment. It\'s been so great to see so many people enjoying growing their own this year. I find being out in the garden and seeing seeds grow very therapeutic and yeah it just makes me feel better! There are lots of exciting things happening here in the Highlands and I\'m really interested to keep learning about it all.',
    'title' => 'Growing their own',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '9.10.20',
    'storyDateFormatted' => '2020-10-09',
    'categories' => 'Seasonal growing, Mental health',
    'imported' => '',
  ],
	[
    'author' => 'Rachel',
    'story-number' => 65,
    'location' => 'Inverness',
    'text' => 'My food story is trying to find cheap and affordable ways to reduce my plastic and also the distance my food has travelled (local produce is the goal, and refill stations). So far, I have been making small swaps that are achievable for someone living on a student budget. I have also been trying to rediscover my love for food, mainly through trying to find healthy recipes and tasty treats.',
    'title' => 'Cheap and affordable',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '11.10.20',
    'storyDateFormatted' => '2020-10-11',
    'categories' => 'Cooking, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Rachel #2',
    'story-number' => 66,
    'location' => 'Inverness',
    'text' => 'I had just moved to Inverness 2 weeks before lockdown. I grew veg in my garden during lockdown (and still now) and gave lots of spare seedlings to my neighbours. It was a great way for me to meet them and start a conversation.',
    'title' => 'Spare seedlings',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '5.10.20',
    'storyDateFormatted' => '2020-10-05',
    'categories' => 'Community sharing, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Anonymous',
    'story-number' => 67,
    'location' => 'Cannich, Beauly',
    'text' => 'We are a small family enjoying growing what we can in amongst busy family life and building a house. We learn something new each season! We are looking forward to connecting with more neighbours to work towards a community model of growing alongside individual gardens.',
    'title' => 'Growing what we can',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '20.10.20',
    'storyDateFormatted' => '2020-10-20',
    'categories' => 'Community sharing, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Anonymous',
    'story-number' => 68,
    'location' => 'Cannich',
    'text' => 'Baking sourdough bread, keeping chickens in the back garden. I’m lucky to have a greenhouse and growing all sorts. Topping up our veg from Robertson’s Farm Shop in Beauly.',
    'title' => 'Growing all sorts',
    'source' => 'Highland Good Food Conversation',
    'storyDate' => '23.10.20',
    'storyDateFormatted' => '2020-10-23',
    'categories' => 'Seasonal growing, Green space',
    'imported' => '',
  ],
	[
    'author' => 'Margaret & Andrew',
    'story-number' => 69,
    'location' => 'Perthshire',
    'text' => 'One thing with people growing their own is collectively they come up with ideas of what to do with gluts of vegetables - sharing on social media - so no need for expensive or exact recipes.',
    'title' => 'Gluts of vegetables',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Community sharing, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Mary #3',
    'story-number' => 70,
    'location' => 'Edinburgh',
    'text' => 'We talked about what was happening in our communities. A lot about food growing, communities pulling together and sharing knowledge, resources and support and picked up on the point Stuart made about time and how working from home gives you the opportunity to mix your day up with a bit of work and bit of weeding and repeat!',
    'title' => 'Opportunity to mix your day up',
    'source' => 'Food Stories Workshop 3',
    'storyDate' => '9.9.20',
    'storyDateFormatted' => '2020-09-09',
    'categories' => 'Community sharing, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Stephen',
    'story-number' => 71,
    'location' => 'Lochaber',
    'text' => 'It’s a really cultural thing in the West Highlands this way of doing it (planting potatoes in ridges with seaweed). And in Ireland the Gaelic word for potatoes is buntàta = tatties. It’s done using seaweed which makes the potatoes nutritionally denser. They are very old, these ridges I mean. These were made by the old guys near me a long time ago, but made using the same method. In the village, we share seed. I’m delivering some today actually to three other crofters. The type I’m sowing in the video is the Lumper, the type that failed in the famine.',
    'title' => 'We share seed',
    'source' => 'Covid Chronicle',
    'storyDate' => '27.5.20',
    'storyDateFormatted' => '2020-05-27',
    'categories' => 'Community sharing, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Erica',
    'story-number' => 72,
    'location' => 'Edinburgh',
    'text' => 'Inspired by a friend\'s purchase of a rice cooker, I also bought a rice cooker. It’s a dream. Watching my friends share as they explore what they cook and how they cook with each other over social media has been a true inspiration during lockdown.',
    'title' => 'A true inspiration',
    'source' => 'Covid Chronicle',
    'storyDate' => '2.11.20',
    'storyDateFormatted' => '2020-11-02',
    'categories' => 'Cooking',
    'imported' => '',
  ],
	[
    'author' => 'Erica #2',
    'story-number' => 73,
    'location' => 'Edinburgh',
    'text' => 'My mother in law is a terrible cook and she always bakes cakes that fall in the middle. She says she’s tried correcting everything. However, I’ve introduced her to the box cake. I love a good Betty Crocker/Duncan Hines devil’s food chocolate cake, and I will buy the icing in the tub, too. It’s such an American indulgence - all that sugar. But it comes out perfect and moist every time, and I can do it in 20 minutes with a few eggs and oil for under £5.',
    'title' => 'An American indulgence',
    'source' => 'Covid Chronicle',
    'storyDate' => '2.11.20',
    'storyDateFormatted' => '2020-11-02',
    'categories' => 'Cooking',
    'imported' => '',
  ],
	[
    'author' => 'Joe #2',
    'story-number' => 74,
    'location' => 'Glasgow',
    'text' => 'This crisis has highlighted the interconnectedness of society and the vulnerabilities that are brought about to everyone when our food system is unfit for purpose and we lack adequate safety nets. We need to take this as an opportunity to rethink and properly restructure our food and welfare systems. The right to food and a cash based approach to food poverty have long been spoken about as aims of the Scottish government and now, as we look to “build back better”, more than ever they are necessary. I believe that community projects have a huge role to play in our food systems future, but let us move forward so it is through education and empowerment, building community, and developing local food provision, green space, and food hubs, rather than scrambling about trying to plug holes in our broken food and welfare systems.',
    'title' => 'Interconnectedness of society',
    'source' => 'SFC Blog',
    'storyDate' => '12.6.20',
    'storyDateFormatted' => '2020-06-12',
    'categories' => 'Community sharing, Food insecurity, Green space, Inequality, Environmental concerns, Right to food',
    'imported' => '',
  ],
	[
    'author' => 'Lewis',
    'story-number' => 75,
    'location' => 'Edinburgh',
    'text' => 'Through lockdown I initially had more time to experiment a bit more with food and cook at home for my partner. We definitely make more effort to be a bit more adventurous with our grocery shopping - we got really bored of the same standardised supermarket things, we\'ve been actively making more of an effort to visit the wonderful diverse array of local middle eastern, continental European and Asian shops in Leith to buy things we have never tried before and giving it a go (and very conscious of supporting local small businesses too). We have been really aware of the privilege of this too, so trying to ask homeless people if they want us to pick up food and supporting national and local food bank charities including the amazing Scran Academy and Social Bite brownies too to our community partners as we\'ve really been missing the usual tea and biscuits that fuel community engagement and relationship building!',
    'title' => 'Community engagement',
    'source' => 'Covid Chronicle',
    'storyDate' => '2.11.20',
    'storyDateFormatted' => '2020-11-02',
    'categories' => 'Community sharing, Cooking, Local economy, Inequality',
    'imported' => '',
  ],
	[
    'author' => 'Daisy',
    'story-number' => 76,
    'location' => 'Inverness',
    'text' => 'I work in organic farming and am really concerned with the food system. I have seen quite a few community sharing initiatives arising as a response to to these times. I also know a lot of people who have been inspired to grow their own.',
    'title' => 'Sharing initiatives',
    'source' => 'Food Stories workshop 4',
    'storyDate' => '12.9.20',
    'storyDateFormatted' => '2020-09-12',
    'categories' => 'Community sharing, Seasonal growing',
    'imported' => '',
  ],
	[
    'author' => 'Lottie',
    'story-number' => 77,
    'location' => 'Glasgow',
    'text' => 'As the world battles COVID-19, the climate and nature crisis, racial and social injustice and beyond, this food story is one of extreme fortune and appreciation while spending Spring/Summer at home in rural Scotland. I went home to my parents house for a weekend, and instead stayed for the for 4 months of lockdown. Privileged with a garden – and filling furloughed hours - growing food became my new obsession. My plant babies (including herbs, tomatoes, leafy greens, cauliflower and courgettes) brought me daily joy. Every time they made a tiny bit of progress, I shared it with anyone who’d listen. I realised just how long it takes for a single bit of food to grow, previously naïve to the laborious process and vulnerability of plants to external conditions – too much/little water, mice, insects, the highly unpredictable Scottish weather to name a few. Each change in the season brought new excitement and challenges with it. In late summer, we ate a meal made entirely of home-grown veggies and my partner commented that it was probably the lowest environmental impact meal we’d ever had. This novice, small scale experience has given me a passionate appreciation for home-grown goodies. Ever aware of how lucky the experience, and now back in my city flat, I am determined to keep a seasonal approach to cooking, with a small windowsill herb garden and new veg box subscription and far more thought about exactly how much time and energy goes into producing each item. I hope the future sees investment in organic, locally produced veggies with a healthier, more environmentally friendly food systems as the norm, rather than a luxury.',
    'title' => 'Daily joy',
    'source' => 'Covid Chronicle',
    'storyDate' => '6.11.20',
    'storyDateFormatted' => '2020-11-06',
    'categories' => 'Cooking, Seasonal growing, Green space, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Ruby',
    'story-number' => 78,
    'location' => 'Edinburgh',
    'text' => 'I’ve been in awe of people’s passion and creativity for food during this pandemic. I’ve eagerly watched a friend innovatively – and successfully – grow veg in a repurposed sled in her Edinburgh flat, and seen my sister transform her disused allotment into an organic kitchen garden that’s also acted as a haven for wildlife. This health crisis has taught me that we do need a different food system, one that is more diverse, resilient and adaptable. Above all, it’s shown me that we need a system that is fair to both the people and planet. To me, a system that supports more low carbon kitchen and community gardeners can take us a step closer to delivering this vision.',
    'title' => 'People and planet',
    'source' => 'Covid Chronicle',
    'storyDate' => '3.11.20',
    'storyDateFormatted' => '2020-11-03',
    'categories' => 'Cooking, Green space, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Jock',
    'story-number' => 79,
    'location' => 'Edinvale Farm, Forres',
    'text' => 'I was having sleepless nights when people were being told not to eat at restaurants because that was 80% of our business that was going to disappear overnight. We very quickly managed to realign, and we have been incredibly lucky with the support we have had locally and nationally from people coming and buying from our local shop or ordering online. We are now doing a months’ worth of work every two to three days, but our food service business is still patchy depending on the geography of our customers. Those on the north and west coast continue to be busy however those inland are a bit quieter. We are helping the local community by teaming up with local business who don’t have the same resources as us and making their deliveries for them. We have also been going to the Co-op to collect milk and butter for people that are self-isolating. That way, vulnerable people who can’t leave their homes don’t need to wait for weeks to receive their supermarket orders. We have put in an honesty shop up at the farm to serve the local community and those wishing to travel from further afield. We stock the essentials and try and support other local producers so that they have an outlet for their products. For example eggs from the farm next door (NFFN).',
    'title' => 'Sleepless nights',
    'source' => 'NFFN',
    'storyDate' => '16.4.20',
    'storyDateFormatted' => '2020-04-16',
    'categories' => 'Community sharing, Food insecurity, Supply chains, Local economy, Isolation, Seasonal growing, Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Diana',
    'story-number' => 80,
    'location' => 'Dundee',
    'text' => 'Most of us like wild roses and their berries help us through the winter. In Europe and Western Asia it is the native sweetbriar rose (rosa rubiginosa). It is a deciduous shrub reaching 2-3 m high and can serve as an excellent hedge plant. There are quite some health benefits collecting rose hips for your home. They can be eaten raw as berries (though take care of the hairs inside the fruit). Most often they are used for herbal tea, jam, jelly, syrup, soup, wine, pies and bread. Wild rose hips are very high in vitamin C, and as we are facing a dark pandemic winter, we need to enhance our vitamin intake. The hips also contain several carotenoids such as b-carotene, lutein, zeaxanthin and lycopene. These antioxidants are very important, especially in winter time. If you have rose hip bushes close by, do go out and collect some. Dry them at home and do make your own tea. Best is to let water boil and put some dried hips into the boiling water and let it boil for a couple of minutes. You can also throw a bit of ginger in there. Enjoy this tea spiked with vitamins and antioxidants. Alternatively I suggest you may want to also use rose hips for your fruit salads, which will give them an additional flair.',
    'title' => 'Help us through the winter',
    'source' => 'Covid Chronicle',
    'storyDate' => '6.11.20',
    'storyDateFormatted' => '2020-11-06',
    'categories' => 'Seasonal growing, Physical health',
    'imported' => '',
  ],
	[
    'author' => 'Coop',
    'story-number' => 81,
    'location' => 'Brodick, Isle of Arran',
    'text' => 'We set up a pick, pack and delivery service in response to Covid-19 which saw up to 500 orders a week being processed, on an island with 4500 full time residents. We have employed extra shop and delivery staff and also worked closely with community groups to identify vulnerable people and arrange food delivery. Also, we moved the foodshare (in conjunction with Arran Eco Savvy) instore for the time being to ensure food waste minimisation activities continue throughout the pandemic period.',
    'title' => 'Vulnerable people',
    'source' => 'Covid Chronicle',
    'storyDate' => '6.11.20',
    'storyDateFormatted' => '2020-11-06',
    'categories' => 'Supply chains, Physical health, Environmental concerns',
    'imported' => '',
  ],
	[
    'author' => 'Inverness Botanic Gardens',
    'story-number' => 82,
    'location' => 'Inverness',
    'text' => 'Our sales and Nursery greenhouses, which would normally have house plants/council flowers, instead switched to being used for vegetable production – a successional planting scheme was drawn up by our knowledgeable gardener who is also a grower. On top of the overall produce, we also have had continuous supply of fresh salad leaves throughout these months. Due to the isolating nature of the lockdown, the more widely recognised benefits of gardening to benefit mental wellbeing formed the basis of providing seed packets to vulnerable and shielding groups. The “Green Health Packs” were trialled initially in the Badenoch and Strathspey area. They proved to be such a success that we provided to many rural areas thereafter. We were actively seeking out partnerships with diversity of local groups or individuals to create links between our unused resources or newly created supply and outlets that were in demand. The intention was to look for gaps in the local food systems and trying to fill them at least a bit. Thus, we have been able to provide our produce to a local veg box retailer, or a charity Inverness Foodstuff (at Ness Bank Church) preparing meals for those in need. Additionally, due to the connections of some of our staff members to local allotments, after finishing our planting, a surplus of high-quality vegetable seedlings were donated there.',
    'title' => 'Look for gaps',
    'source' => 'Covid Chronicle',
    'storyDate' => '6.11.20',
    'storyDateFormatted' => '2020-11-06',
    'categories' => 'Community sharing, Food insecurity, Local economy, Isolation, Mental health',
    'imported' => '',
  ],
];

// header('Content-Type: application/json');
// echo json_encode($data);

// --- CHECK IF ALL WERE IMPORTED

foreach ($data as $d) {
	$slug = str::slug($d['title']);
	if (pages("stories")->childrenAndDrafts()->has("stories/$slug")) {
		echo " - YES - ";
	}
	echo $slug;
	echo "<br>";
}

exit();


// --- IMPORT

$kirby->impersonate('kirby');

foreach ($data as $d) {
	if ($d["imported"] === 1) {
		echo "---<br/>";
		continue;
	}

	try {
		$slug = str::slug($d['title']);
	  $registration = page("stories")->createChild([
	    'slug'     => $slug,
	    'template' => 'story',
	    'content'  => [
				"title"      	=> $d["title"],
				"text"      	=> $d["text"],
				"categories"	=> $d["categories"],
				"storyDate" 	=> $d["storyDateFormatted"],
				"author"    	=> $d["author"],
				"source"    	=> $d["source"],
				"place"     	=> $d["location"],
	    ],
	  ]);

	  if ($registration) {
  		echo "SUCCESS". $slug;
	  } else {
  		echo "FAILED". $slug;
	  }

	} catch (Exception $e) {
	  echo 'Your registration failed: ' . $e->getMessage();
	}

	echo "<br>";

}






